const rawManha = `
9º A 9º B 9º C 9º D 9º E 1º A 1º B

   07:00 HIST (ELAINE) LP (ALAYNE) MAT (GREICE) MAT (MARCO) ART (DANIELA) ED.FIS (JULIANA) GEO (ARMS)

   07:50 HIST (ELAINE) LP (ALAYNE) MAT (GREICE) GEO (ARMS) MAT (MARCO) INGL (KARINA) ED.FIN (CAMILA)

Seg 08:40 MAT (GREICE) RED/LT (ALAYNE) INGL (KARINA) RED/LT (NOÊMIA) MAT (MARCO) GEO (ARMS) ART (DANIELA)

   09:50 LP (ALAYNE) GEO (ARMS) PV (DANIELA) LP (SIMONE) RED/LT (NOÊMIA) MAT (GREICE) BIO (LU PUTTI)

   10:40 ART (DANIELA) HIST (ELAINE) LP (ALAYNE) LP (SIMONE) RED/LT (NOÊMIA) MAT (GREICE) INGL (KARINA)

   11:30 RED/LT (ALAYNE) CIEN (LU PUTTI) RED/LT (NOÊMIA) MAT (MARCO) OE-LP (DANIELA) FILO (JAIR) LP (MÁRCIA)

   07:00 CIEN (LU PUTTI) ED.FIS (JULIANA) CIEN (TAMIRIS) MAT (MARCO) HIST (RAFAELA) MAT (GREICE) MAT (MATEMÁTICA)

   07:50 MAT (GREICE) LP (ALAYNE) CIEN (TAMIRIS) MAT (MARCO) HIST (RAFAELA) HIST (ELAINE) GEO (ARMS)

Ter 08:40 MAT (GREICE) CIEN (LU PUTTI) GEO (ARMS) HIST (RAFAELA) CIEN (TAMIRIS) FILO (JAIR) INGL (KARINA)

   09:50 GEO (ARMS) CIEN (LU PUTTI) MAT (GREICE) CIEN (TAMIRIS) PV (DANIELA) LP (MÁRCIA) QUIM (CAROLINE)

   10:40 INGL (KARINA) MAT (GREICE) RED/LT (NOÊMIA) CIEN (TAMIRIS) MAT (MARCO) BIO (LU PUTTI) LP (MÁRCIA)

   11:30 PV (DANIELA) MAT (GREICE) LP (ALAYNE) RED/LT (NOÊMIA) CIEN (TAMIRIS) ED.FIN (CAMILA) BIO (LU PUTTI)

   07:00 LP (ALAYNE) HIST (ELAINE) ED.FIS (JULIANA) INGL (KARINA) ED.FIS (RODRIGO) ART (SÔNIA) FILO (JAIR)

   07:50 HIST (ELAINE) ED.FIS (JULIANA) OE-LP (ALAYNE) INGL (KARINA) ED.FIS (RODRIGO) RED/LT (MÁRCIA) MAT (MATEMÁTICA)

Qua 08:40 ED.FIS (JULIANA) RED/LT (ALAYNE) HIST (ELAINE) ED.FIS (RODRIGO) INGL (KARINA) ART (SÔNIA) MAT (MATEMÁTICA)

   09:50 GEO (ARMS) MAT (GREICE) OE-MAT (GALASTRI) PV (DANIELA) LP (SIMONE) FIS (PAULO) LP (MÁRCIA)

   10:40 MAT (GREICE) INGL (KARINA) LP (ALAYNE) LP (SIMONE) OE-MAT (GALASTRI) QUIM (CAROLINE) ART (DANIELA)

   11:30 MAT (GREICE) OE-LP (ALAYNE) GEO (ARMS) ED.FIS (RODRIGO) OE-MAT (GALASTRI) LP (MÁRCIA) HIST (ELAINE)

   07:00 RED/LT (ALAYNE) MAT (GREICE) HIST (ELAINE) MAT (MARCO) OE-LP (DANIELA) QUIM (CAROLINE) MAT (MATEMÁTICA)

   07:50 CIEN (LU PUTTI) MAT (GREICE) ED.FIS (JULIANA) GEO (ARMS) MAT (MARCO) INGL (KARINA) FIS (PAULO)

Qui 08:40 CIEN (LU PUTTI) LP (ALAYNE) MAT (GREICE) OE-LP (DANIELA) MAT (MARCO) ED.FIS (JULIANA) QUIM (CAROLINE)

   09:50 OE-LP (ALAYNE) CIEN (LU PUTTI) MAT (GREICE) HIST (RAFAELA) LP (SIMONE) GEO (ARMS) RED/LT (MÁRCIA)

   10:40 OE-MAT (GALASTRI) INGL (KARINA) LP (ALAYNE) HIST (RAFAELA) GEO (ARMS) MAT (GREICE) RED/LT (MÁRCIA)

   11:30 LP (ALAYNE) OE-MAT (GALASTRI) INGL (KARINA) LP (SIMONE) HIST (RAFAELA) LP (MÁRCIA) FILO (JAIR)

   07:00 INGL (KARINA) OE-MAT (GALASTRI) HIST (ELAINE) CIEN (TAMIRIS) LP (SIMONE) FIS (PAULO) LP (MÁRCIA)

   07:50 LP (ALAYNE) PV (DANIELA) OE-MAT (GALASTRI) CIEN (TAMIRIS) LP (SIMONE) HIST (ELAINE) ED.FIN (CAMILA)

Sex 08:40 OE-MAT (GALASTRI) GEO (ARMS) OE-LP (ALAYNE) ART (DANIELA) CIEN (TAMIRIS) BIO (LU PUTTI) HIST (ELAINE)

   09:50 ED.FIS (JULIANA) OE-LP (ALAYNE) ART (DANIELA) OE-MAT (GALASTRI) CIEN (TAMIRIS) LP (MÁRCIA) FIS (PAULO)

   10:40 OE-LP (ALAYNE) ART (DANIELA) CIEN (TAMIRIS) OE-MAT (GALASTRI) GEO (ARMS) ED.FIN (CAMILA) ED.FIS (JULIANA)

   11:30 CIEN (LU PUTTI) HIST (ELAINE) CIEN (TAMIRIS) OE-LP (DANIELA) INGL (KARINA) RED/LT (MÁRCIA) ED.FIS (JULIANA)



1º C 1º D 2º A 2º B 2º C 3º A 3º B

   07:00 ED.FIN (CAMILA) BIO (LU PUTTI) RED/LT (ANA PAULA) LP (MÁRCIA) PROG (MAIARA) INGL (KARINA) ORT (JAIR)

   07:50 ED.FIS (JULIANA) LP (SIMONE) RED/LT (ANA PAULA) LP (MÁRCIA) PROG (MAIARA) BIOTEC (LU PUTTI) ORT (JAIR)

Seg 08:40 BIO (LU PUTTI) LP (SIMONE) LP (MÁRCIA) HIST (ELAINE) ED.FIS (JULIANA) MAT (CAMILA) FSOCMO (JAIR)

   09:50 MAT (MARCO) INGL (KARINA) SOCIO (JAIR) ED.FIN (GABRIEL) HIST (ELAINE) MAT (CAMILA) LP (MÁRCIA)

   10:40 MAT (MARCO) GEO (ARMS) SOCIO (JAIR) MAT (CAMILA) ED.FIN (GABRIEL) PROG (MAIARA) LP (MÁRCIA)

   11:30 INGL (KARINA) MAT (FABIANO) ED.FIN (GABRIEL) GEO (ARMS) MAT (CAMILA) OE-MAT (GREICE) OE-MAT (MAIARA)

   07:00 LP (SIMONE) FILO (JAIR) INGL (KARINA) LP (MÁRCIA) MAT (CAMILA) HIST (ELAINE) OE-LP (ALAYNE)

   07:50 LP (SIMONE) FILO (JAIR) INGL (KARINA) ED.FIS (JULIANA) FIS (PAULO) MAT (CAMILA) LP (MÁRCIA)

Ter 08:40 MAT (MARCO) LP (SIMONE) HIST (ELAINE) FIS (PAULO) LP (ALAYNE) MAT (CAMILA) LP (MÁRCIA)

   09:50 MAT (MARCO) MAT (FABIANO) MAT (CAMILA) SOCIO (JAIR) LP (ALAYNE) FIS (PAULO) HIST (ELAINE)

   10:40 HIST (ELAINE) FIS (PAULO) GEO (ARMS) MAT (CAMILA) SOCIO (JAIR) OE-LP (ALAYNE) ARTDG (DANIELA)

   11:30 FIS (PAULO) MAT (FABIANO) LP (MÁRCIA) INGL (KARINA) SOCIO (JAIR) Q.APL (CAROLINE) GEOP (ARMS)

   07:00 ART (ARTE) MAT (FABIANO) LP (MÁRCIA) EMPREN (EMPREEM) QUIM (CAROLINE) EMPREN (VALDEMAR) OE-MAT (MAIARA)

   07:50 ART (ARTE) ED.FIN (FABIANO) LID (JAIR) PROG (MAIARA) QUIM (CAROLINE) EMPREN (VALDEMAR) MAT (CAMILA)

Qua 08:40 QUIM (CAROLINE) ED.FIN (FABIANO) MAT (CAMILA) PROG (MAIARA) EMPREN (EMPREEM) RED/LT (MÁRCIA) FSOCMO (JAIR)

   09:50 QUIM (CAROLINE) ART (VIVIANE) BIO (LU PUTTI) INGL (KARINA) LP (ALAYNE) HIST (ELAINE) ED.FIS (JULIANA)

   10:40 GEO (ARMS) ART (VIVIANE) ED.FIS (JULIANA) MAT (CAMILA) BIO (LU PUTTI) LP (MÁRCIA) HIST (ELAINE)

   11:30 LP (SIMONE) BIO (LU PUTTI) FIS (PAULO) QUIM (CAROLINE) MAT (CAMILA) ED.FIS (JULIANA) INGL (KARINA)

   07:00 FIS (PAULO) INGL (KARINA) MAT (CAMILA) BIO (LU PUTTI) GEO (ARMS) LP (MÁRCIA) RED/LT (FABIANA)

   07:50 ED.FIN (CAMILA) RED/LT (FABIANA) HIST (ELAINE) LP (MÁRCIA) LP (ALAYNE) Q.APL (CAROLINE) PV (DANIELA)

Qui 08:40 LP (SIMONE) RED/LT (FABIANA) GEO (ARMS) MAT (CAMILA) INGL (KARINA) RED/LT (MÁRCIA) FIS (PAULO)

   09:50 HIST (ELAINE) QUIM (CAROLINE) LID (JAIR) RED/LT (FABIANA) INGL (KARINA) FIS (PAULO) MAT (CAMILA)

   10:40 BIO (LU PUTTI) LP (SIMONE) FIS (PAULO) SOCIO (JAIR) HIST (ELAINE) PV (DANIELA) MAT (CAMILA)

   11:30 GEO (ARMS) FIS (PAULO) BIO (LU PUTTI) HIST (ELAINE) RED/LT (FABIANA) OE-MAT (GREICE) ARTDG (DANIELA)

   07:00 RED/LT (FABIANA) ED.FIS (JULIANA) MAT (CAMILA) GEO (ARMS) ED.FIN (GABRIEL) PROG (MAIARA) OE-LP (ALAYNE)

   07:50 RED/LT (FABIANA) ED.FIS (JULIANA) QUIM (CAROLINE) ED.FIN (GABRIEL) BIO (LU PUTTI) LP (MÁRCIA) GEOP (ARMS)

Sex 08:40 ED.FIS (JULIANA) QUIM (CAROLINE) ED.FIN (GABRIEL) FIS (PAULO) MAT (CAMILA) LP (MÁRCIA) INGL (KARINA)

   09:50 INGL (KARINA) HIST (ELAINE) ORT (FÁBIO) QUIM (CAROLINE) GEO (ARMS) BIOTEC (LU PUTTI) RED/LT (FABIANA)

   10:40 FILO (FÁBIO) HIST (ELAINE) LP (MÁRCIA) BIO (LU PUTTI) RED/LT (FABIANA) INGL (KARINA) FIS (PAULO)

   11:30 FILO (FÁBIO) GEO (ARMS) QUIM (CAROLINE) RED/LT (FABIANA) FIS (PAULO) OE-LP (ALAYNE) MAT (CAMILA)



3º C

   07:00 LP (SIMONE)

   07:50 OE-LP (DANIELA)

Seg 08:40 PROG (MAIARA)

   09:50 PROG (MAIARA)

   10:40 BIOTEC (LU PUTTI)

   11:30 LP (SIMONE)

   07:00 FIS (PAULO)

   07:50 BIOTEC (LU PUTTI)

Ter 08:40 ED.FIS (JULIANA)

   09:50 INGL (KARINA)

   10:40 Q.APL (CAROLINE)

   11:30 HIST (ELAINE)

   07:00 MAT (CAMILA)

   07:50 OE-MAT (OE- MAT)

Qua 08:40 OE-MAT (OE- MAT)

   09:50 MAT (CAMILA)

   10:40 FIS (PAULO)

   11:30 OE-LP (DANIELA)

   07:00 LP (SIMONE)

   07:50 LP (SIMONE)

Qui 08:40 HIST (ELAINE)

   09:50 PV (DANIELA)

   10:40 RED/LT (FABIANA)

   11:30 MAT (CAMILA)

   07:00 Q.APL (CAROLINE)

   07:50 INGL (KARINA)

Sex 08:40 RED/LT (FABIANA)

   09:50 MAT (CAMILA)

   10:40 EMPREN (VALDEMAR)

   11:30 EMPREN (VALDEMAR)
`;

const rawTarde = `
6º A 6º B 6º C 6º D 6º E 7º A

   12:40 GEO (FÁBIO) LP (ELISANGELA) CIEN (JAQUELINE) INGL (ANA PAULA) ART (ARTE) MAT (GABRIEL)

   13:30 GEO (FÁBIO) LP (ELISANGELA) CIEN (JAQUELINE) ART (ARTE) LP (ANA BRISOLAR) MAT (GABRIEL)

Seg 14:20 HIST (RAFAELA) MAT (GABRIEL) INGL (ANA PAULA) LP (ELISANGELA) GEO (FÁBIO) REDLET (ELISA)

   15:30 LP (ELISANGELA) MAT (GABRIEL) TEC (VINÍCIUS) CIEN (JAQUELINE) HIST (RAFAELA) PV (FÁBIO)

   16:20 CIEN (JAQUELINE) HIST (RAFAELA) GEO (FÁBIO) REDLET  (ELISANGELA) MAT (GABRIEL) LP (ELISA)

   17:10 MAT (GABRIEL) REDLET  (ELISANGELA) INGL (ANA PAULA) TEC (VINÍCIUS) ED FIN (FABIANO) ART (ARTE)

   12:40 LP (ELISANGELA) ART (DANIELA) GEO (FÁBIO) MAT (GABRIEL) TEC (VINÍCIUS) CIEN (JAQUELINE)

   13:30 TEC (VALDEMAR) ART (DANIELA) GEO (FÁBIO) REDLET  (ELISANGELA) MAT (GABRIEL) LP (ELISA)

Ter 14:20 MAT (GABRIEL) ED FIN (GALASTRI) ART (DANIELA) GEO (FÁBIO) CIEN (JAQUELINE) INGL (ANA PAULA)

   15:30 TEC (VALDEMAR) PV (DANIELA) MAT (GABRIEL) INGL (ANA PAULA) CIEN (JAQUELINE) ED FIN (GALASTRI)

   16:20 ART (DANIELA) TEC (VALDEMAR) MAT (GABRIEL) LP (ELISANGELA) ART (ARTE) ED FIN (GALASTRI)

   17:10 ART (DANIELA) GEO (FÁBIO) LP (ELISANGELA) ED FIN (GALASTRI) HIST (RAFAELA) MAT (GABRIEL)

   12:40 REDLET  (ELISANGELA) CIEN (JAQUELINE) HIST (RAFAELA) MAT (GABRIEL) INGL (ANA PAULA) TEC (VINÍCIUS)

   13:30 MAT (GABRIEL) LP (ELISANGELA) TEC (VINÍCIUS) HIST (RAFAELA) INGL (ANA PAULA) ED FIS (RODRIGO)

Qua 14:20 GEO (FÁBIO) LP (ELISANGELA) ED FIS (RODRIGO) CIEN (JAQUELINE) LP (ANA BRISOLAR) MAT (GABRIEL)

   15:30 CIEN (JAQUELINE) ED FIS (RODRIGO) MAT (GABRIEL) LP (ELISANGELA) LP (ANA BRISOLAR) ART (ARTE)

   16:20 CIEN (JAQUELINE) ED FIS (RODRIGO) MAT (GABRIEL) ART (ARTE) ED FIN (FABIANO) TEC (VINÍCIUS)

   17:10 INGL (ANA PAULA) HIST (RAFAELA) LP (ELISANGELA) GEO (FÁBIO) MAT (GABRIEL) CIEN (JAQUELINE)

   12:40 ED FIN (GALASTRI) INGL (ANA PAULA) LP (ELISANGELA) MAT (GABRIEL) GEO (FÁBIO) ED FIS (RODRIGO)

   13:30 ED FIN (GALASTRI) MAT (GABRIEL) ED FIS (RODRIGO) TEC (VINÍCIUS) GEO (FÁBIO) REDLET (ELISA)

Qui 14:20 INGL (ANA PAULA) TEC (VALDEMAR) REDLET  (ELISANGELA) ED FIN (GALASTRI) MAT (GABRIEL) CIEN (JAQUELINE)

   15:30 MAT (GABRIEL) GEO (FÁBIO) ED FIN (GALASTRI) LP (ELISANGELA) LP (ANA BRISOLAR) LP (ELISA)

   16:20 MAT (GABRIEL) GEO (FÁBIO) ED FIN (GALASTRI) HIST (RAFAELA) REDLET (ANA PAULA) LP (ELISA)

   17:10 HIST (RAFAELA) ED FIN (GALASTRI) MAT (GABRIEL) GEO (FÁBIO) TEC (VINÍCIUS) GEO (HENRIQUE)

   12:40 LP (ELISANGELA) INGL (ANA PAULA) ART (DANIELA) MAT (GABRIEL) CIEN (JAQUELINE) HIST (RAFAELA)

   13:30 LP (ELISANGELA) CIEN (JAQUELINE) PV (DANIELA) MAT (GABRIEL) PV (JAIR) HIST (RAFAELA)

Sex 14:20 PV (DANIELA) CIEN (JAQUELINE) LP (ELISANGELA) ED FIS (SILMARI) MAT (GABRIEL) GEO (HENRIQUE)

   15:30 REDLET  (ELISANGELA) MAT (GABRIEL) HIST (RAFAELA) ED FIS (SILMARI) REDLET (ANA PAULA) GEO (HENRIQUE)

   16:20 ED FIS (IVO) MAT (GABRIEL) REDLET  (ELISANGELA) CIEN (JAQUELINE) ED FIS (SILMARI) INGL (ANA PAULA)

   17:10 ED FIS (IVO) REDLET  (ELISANGELA) CIEN (JAQUELINE) PV (JAIR) ED FIS (SILMARI) MAT (GABRIEL)



7º B 7º C 7º D 7º E 8º A 8º B

   12:40 HIST (RAFAELA) LP (ELISA) MAT (CRIS CAZALE) ED FIS (JULIANA) MAT (SAMANTA) TEC (VINÍCIUS)

   13:30 HIST (RAFAELA) LP (ELISA) MAT (CRIS CAZALE) INGL (ANA PAULA) MAT (SAMANTA) ART (SÔNIA)

Seg 14:20 MAT (CRIS CAZALE) PV (JAIR) ART (ARTE) CIEN (JAQUELINE) MAT (SAMANTA) CIEN (LUCIANA)

   15:30 MAT (CRIS CAZALE) REDLET (ELISA) INGL (ANA PAULA) ED FIN (FABIANO) ART (SÔNIA) CIEN (LUCIANA)

   16:20 TEC (VINÍCIUS) MAT (CRIS CAZALE) ED FIS (JULIANA) ART (ARTE) CIEN (LUCIANA) INGL (ANA PAULA)

   17:10 CIEN (JAQUELINE) MAT (CRIS CAZALE) ED FIS (JULIANA) MAT (VALDEMAR) REDLET (ELISA) MAT (MARCO)

   12:40 ED FIN (GALASTRI) REDLET (ELISA) HIST (RAFAELA) MAT (VALDEMAR) MAT (SAMANTA) GEO (ARMS)

   13:30 ED FIN (GALASTRI) INGL (ANA PAULA) CIEN (JAQUELINE) LP (CLAUDEMIR) MAT (SAMANTA) GEO (ARMS)

Ter 14:20 LP (ELISANGELA) LP (ELISA) LP (CLAUDEMIR) MAT (VALDEMAR) GEO (ARMS) HIST (RAFAELA)

   15:30 LP (ELISANGELA) LP (ELISA) GEO (HENRIQUE) HIST (RAFAELA) GEO (ARMS) CIEN (LUCIANA)

   16:20 REDLET (ANA PAULA) CIEN (JAQUELINE) GEO (HENRIQUE) HIST (RAFAELA) CIEN (LUCIANA) LP (ELISA)

   17:10 GEO (HENRIQUE) ART (ARTE) INGL (ANA PAULA) CIEN (JAQUELINE) LP (ELISA) ED FIS (IVO)

   12:40 MAT (CRIS CAZALE) ED FIN (FABIANO) ART (ARTE) REDLET (NOÊMIA) INGL (KARINA) ED FIN (CAMILA)

   13:30 GEO (HENRIQUE) CIEN (JAQUELINE) LP (CLAUDEMIR) REDLET (NOÊMIA) INGL (KARINA) ED FIN (CAMILA)

Qua 14:20 MAT (CRIS CAZALE) GEO (HENRIQUE) LP (CLAUDEMIR) ART (ARTE) TEC (VINÍCIUS) INGL (ANA PAULA)

   15:30 INGL (ANA PAULA) MAT (CRIS CAZALE) GEO (HENRIQUE) ED FIN (FABIANO) ED FIN (ED. FINANCEIRA) HIST (RAFAELA)

   16:20 LP (ELISANGELA) MAT (CRIS CAZALE) HIST (RAFAELA) INGL (ANA PAULA) ED FIN (ED. FINANCEIRA) MAT (MARCO)

   17:10 ED FIS (RODRIGO) ART (ARTE) MAT (CRIS CAZALE) MAT (VALDEMAR) TEC (VINÍCIUS) MAT (MARCO)

   12:40 MAT (CRIS CAZALE) GEO (HENRIQUE) CIEN (JAQUELINE) ED FIS (JULIANA) PV (MÁRCIA) REDLET (ELISA)

   13:30 LP (ELISANGELA) CIEN (JAQUELINE) REDLET (NOÊMIA) LP (CLAUDEMIR) CIEN (LUCIANA) PV (MÁRCIA)

Qui 14:20 ED FIS (RODRIGO) HIST (RAFAELA) REDLET (NOÊMIA) LP (CLAUDEMIR) LP (ELISA) MAT (MARCO)

   15:30 CIEN (JAQUELINE) ED FIS (RODRIGO) MAT (CRIS CAZALE) GEO (HENRIQUE) CIEN (LUCIANA) TEC (VINÍCIUS)

   16:20 TEC (VINÍCIUS) ED FIS (RODRIGO) MAT (CRIS CAZALE) CIEN (JAQUELINE) HIST (ELAINE) CIEN (LUCIANA)

   17:10 ART (ARTE) MAT (CRIS CAZALE) CIEN (JAQUELINE) MAT (VALDEMAR) HIST (ELAINE) LP (ELISA)

   12:40 ART (ARTE) GEO (HENRIQUE) PV (JAIR) TEC (VIVIANE) REDLET (ELISA) ED FIS (IVO)

   13:30 GEO (HENRIQUE) INGL (ANA PAULA) LP (CLAUDEMIR) TEC (VIVIANE) ED FIS (IVO) LP (ELISA)

Sex 14:20 REDLET (ANA PAULA) HIST (RAFAELA) TEC (VIVIANE) LP (CLAUDEMIR) ED FIS (IVO) LP (ELISA)

   15:30 CIEN (JAQUELINE) ED FIN (FABIANO) TEC (VIVIANE) PV (JAIR) LP (ELISA) MAT (MARCO)

   16:20 PV (JAIR) TEC (VIVIANE) ED FIN (FABIANO) GEO (HENRIQUE) LP (ELISA) HIST (RAFAELA)

   17:10 INGL (ANA PAULA) TEC (VIVIANE) ED FIN (FABIANO) GEO (HENRIQUE) HIST (ELAINE) REDLET (ELISA)



8º C 8º D 8º E

   12:40 PV (JAIR) ART (SÔNIA) PV (CAROLINE)

   13:30 CIEN (LUCIANA) PV (CAROLINE) TEC (VINÍCIUS)

Seg 14:20 ART (SÔNIA) TEC (VINÍCIUS) REDLET (ANA BRISOLAR)

   15:30 MAT (MARCO) LP (ANA BRISOLAR) ART (ARTE)

   16:20 MAT (MARCO) LP (ANA BRISOLAR) ED FIN (FABIANO)

   17:10 HIST (RAFAELA) GEO (FÁBIO) LP (ANA BRISOLAR)

   12:40 INGL (ANA PAULA) ED FIS (IVO) CIEN (TAMIRIS)

   13:30 CIEN (LUCIANA) CIEN (TAMIRIS) ED FIS (IVO)

Ter 14:20 CIEN (LUCIANA) TEC (VINÍCIUS) ED FIS (IVO)

   15:30 MAT (MARCO) ED FIS (IVO) GEO (FÁBIO)

   16:20 ED FIS (IVO) REDLET (ANA BRISOLAR) GEO (FÁBIO)

   17:10 TEC (VINÍCIUS) ED FIN (FABIANO) LP (ANA BRISOLAR)

   12:40 REDLET (ALAYNE) HIST (HENRIQUE) MAT (VALDEMAR)

   13:30 REDLET (ALAYNE) ED FIN (FABIANO) MAT (VALDEMAR)

Qua 14:20 HIST (RAFAELA) MAT (VALDEMAR) INGL (NOÊMIA)

   15:30 GEO (FÁBIO) MAT (VALDEMAR) TEC (VINÍCIUS)

   16:20 GEO (FÁBIO) LP (ANA BRISOLAR) HIST (HENRIQUE)

   17:10 LP (ANA BRISOLAR) HIST (HENRIQUE) ED FIN (FABIANO)

   12:40 TEC (VINÍCIUS) MAT (VALDEMAR) INGL (NOÊMIA)

   13:30 INGL (ANA PAULA) MAT (VALDEMAR) HIST (HENRIQUE)

Qui 14:20 CIEN (LUCIANA) GEO (FÁBIO) HIST (HENRIQUE)

   15:30 HIST (RAFAELA) INGL (ANA PAULA) MAT (VALDEMAR)

   16:20 LP (ANA BRISOLAR) HIST (HENRIQUE) MAT (VALDEMAR)

   17:10 MAT (MARCO) INGL (ANA PAULA) REDLET (ANA BRISOLAR)

   12:40 LP (ANA BRISOLAR) CIEN (TAMIRIS) MAT (VALDEMAR)

   13:30 LP (ANA BRISOLAR) MAT (VALDEMAR) CIEN (TAMIRIS)

Sex 14:20 MAT (MARCO) LP (ANA BRISOLAR) CIEN (TAMIRIS)

   15:30 ED FIS (IVO) CIEN (TAMIRIS) LP (ANA BRISOLAR)

   16:20 ED FIN (MARCO) CIEN (TAMIRIS) LP (ANA BRISOLAR)

   17:10 ED FIN (MARCO) REDLET (ANA BRISOLAR) CIEN (TAMIRIS)
`;

const rawNoite = `
1º E 2º D 2º E 3º D 3º E 3º F

   19:00 LP (ELISANGELA) QUI (CAROLINE) HIST (HENRIQUE) MAT (PABLO) FIS (VALDEMAR) RD LET (NOÊMIA)

   19:45 LP (ELISANGELA) MAT (PABLO) QUI (CAROLINE) HIST (HENRIQUE) FIS (VALDEMAR) RD LET (NOÊMIA)

Seg 20:30 HIST (HENRIQUE) MAT (PABLO) QUI (CAROLINE) OE-LP (CLAUDEMIR) OE-MAT (VALDEMAR) LP (NOÊMIA)

   21:30 QUI (CAROLINE) LP (CLAUDEMIR) MAT (PABLO) RD LET (NOÊMIA) OE-MAT (VALDEMAR) HIST (HENRIQUE)

   22:15 QUI (CAROLINE) LP (CLAUDEMIR) ED FIN (VALDEMAR) RD LET (NOÊMIA) HIST (HENRIQUE) MAT (PABLO)

   19:00 LP (ELISANGELA) RD LET (NOÊMIA) BIO (YASMIM) QUI (CAROLINE) OE-MAT (VALDEMAR) FIS (VINÍCIUS)

   19:45 LP (ELISANGELA) FIS (VALDEMAR) RD LET (NOÊMIA) OE-LP (CLAUDEMIR) QUI (CAROLINE) FIS (VINÍCIUS)

Ter 20:30 ART (LARISSA) INGL (REGYS) BIO (YASMIM) FIS (VALDEMAR) LP (NOÊMIA) QUI (CAROLINE)

   21:30 MAT (VALDEMAR) BIO (YASMIM) INGL (REGYS) HIST (HENRIQUE) RD LET (NOÊMIA) QUI (CAROLINE)

   22:15 INGL (REGYS) BIO (YASMIM) FIS (VALDEMAR) QUI (CAROLINE) RD LET (NOÊMIA) HIST (HENRIQUE)

   19:00 GEO (ARMS) ED FIN (VALDEMAR) SOCIO (JAIR) LP (ARIANE) MAT (PABLO) OE-MAT (MAIARA)

   19:45 MAT (VALDEMAR) SOCIO (JAIR) LP (ARIANE) MAT (PABLO) BIO (LU PUTTI) OE-LP (FABIANA)

Qua 20:30 RD LET (NOÊMIA) FIS (VALDEMAR) SOCIO (JAIR) MAT (PABLO) OE-LP (FABIANA) BIO (LU PUTTI)

   21:30 FILO (JAIR) RD LET (NOÊMIA) LP (ARIANE) OE-MAT (VALDEMAR) OE-LP (FABIANA) MAT (PABLO)

   22:15 ED FIN (VALDEMAR) SOCIO (JAIR) RD LET (NOÊMIA) LP (ARIANE) MAT (PABLO) OE-LP (FABIANA)

   19:00 GEO (ARMS) LP (CLAUDEMIR) MAT (PABLO) FIS (VALDEMAR) LP (NOÊMIA) GEO (MATHEUS)

   19:45 HIST (HENRIQUE) LP (CLAUDEMIR) MAT (PABLO) OE-MAT (VALDEMAR) LP (NOÊMIA) GEO (MATHEUS)

Qui 20:30 FIS (FÍSICA) MAT (PABLO) HIST (HENRIQUE) OE-MAT (VALDEMAR) GEO (MATHEUS) LP (NOÊMIA)

   21:30 FIS (FÍSICA) QUI (CAROLINE) ED FIN (VALDEMAR) GEO (MATHEUS) MAT (PABLO) LP (NOÊMIA)

   22:15 RD LET (NOÊMIA) ED FIN (VALDEMAR) GEO (MATHEUS) LP (ARIANE) QUI (CAROLINE) MAT (PABLO)

   19:00 BIO (JAQUELINE) HIST (HENRIQUE) FIS (VALDEMAR) GEO (MATHEUS) LP (NOÊMIA) MAT (PABLO)

   19:45 BIO (JAQUELINE) HIST (HENRIQUE) GEO (MATHEUS) MAT (PABLO) BIO (LU PUTTI) LP (NOÊMIA)

Sex 20:30 ED FIN (VALDEMAR) GEO (MATHEUS) MAT (PABLO) LP (ARIANE) HIST (HENRIQUE) BIO (LU PUTTI)

   21:30 MAT (VALDEMAR) GEO (MATHEUS) LP (ARIANE) BIO (LU PUTTI) MAT (PABLO) OE-MAT (MAIARA)

   22:15 MAT (VALDEMAR) MAT (PABLO) LP (ARIANE) BIO (LU PUTTI) GEO (MATHEUS) OE-MAT (MAIARA)
`;